name: Docker Publish (Edge Images)

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - src/**
      - .github/workflows/**
      - ansible-versions.yml
      - build.sh
jobs:
  build-beta-images:
    uses: ./.github/workflows/service_docker-build-and-publish.yml
    secrets: inherit
    with:
      release_type: 'edge'
