name: Docker Publish (Production Images)

on:
  workflow_dispatch:
  release:
    types: [released]
  # Commenting out until ready
  # schedule:
  #   - cron: '0 8 * * 2'

jobs:
  build-production-images:
    uses: ./.github/workflows/service_docker-build-and-publish.yml
    secrets: inherit
    with:
      release_type: 'latest'

  update_container_readme:
    runs-on: ubuntu-24.04
    name: Push README to Docker Hub
    steps:
      - name: git checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: push README to Dockerhub (ansible)
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: ${{ secrets.DOCKER_HUB_README_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKER_HUB_README_PASSWORD }}
        with:
          destination_container_repo: serversideup/ansible
          provider: dockerhub
          short_description: 'Run Ansible anywhere with a lightwieght and powerful Docker image.'
          readme_file: 'README.md'

      - name: push README to Dockerhub (ansible-core)
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: ${{ secrets.DOCKER_HUB_README_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKER_HUB_README_PASSWORD }}
        with:
          destination_container_repo: serversideup/ansible-core
          provider: dockerhub
          short_description: 'Run Ansible anywhere with a lightwieght and powerful Docker image.'
          readme_file: 'README.md'